services:
  - type: web
    name: rez-coq
    env: node
    buildCommand: |
      apt-get update -qq && \
      apt-get install -y python3 build-essential && \
      npm install
    startCommand: node main.js
    postDeploy: |
      node scripts/setup-postgres.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: rez_coq
          property: connectionString
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_APP_PASSWORD
        sync: false
      - key: HOME
        value: /opt/render/project

  - type: postgresql
    name: rez_coq
    ipAllowList: []
    plan: free 